import { Play } from "next/font/google";
import "./globals.css";

const play = Play({ 
  subsets: ["latin"], 
  display: 'swap', 
  weight: ['400', '700'], 
});

export const metadata = {
  title: "Komponents",
  description: "Generated by create next app",
  icons:{
    icon:['/kImg/favicon.ico?v=2'],
    apple:['/kImg/apple-touch-icon.png?var=2'],
    shortcut:['/kImg/apple-touch-icon.png'] 
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={play.className}>{children}</body>
    </html>
  );
}
