import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Komponents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
          <link rel="shortcut icon" href="https://i.postimg.cc/7LrfPN4s/details.png" />
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
