import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Komponents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Head>
          <link rel="shortcut icon" href="/favicon.ico" />
        </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
